{{- $fullname := include "kube-node-ping-exporter.fullname" . -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-node-ping-exporter.labels" . | nindent 4 }}
{{- with $.Values.configmap.data }}
data: {{- toYaml . | nindent 2 }}
{{- end }}
