apiVersion: v2
name: kube-node-ping-exporter
description: Helm chart for kube-node-ping-exporter. Simple application to send ICMP echo requests that exposes results as Prometheus metrics.
type: application
version: 2.0.0
appVersion: "2.0.0"
kubeVersion: '>=1.20.0-0'
maintainers:
- name: vfabi
